[package]
authors = ["Jason Housley <HousleyJK@gmail.com>"]
description = "Lightweight, event-driven WebSockets for Rust."
documentation = "https://ws-rs.org/docs"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"
name = "ws"
readme = "README.md"
repository = "https://github.com/housleyjk/ws-rs"
version = "0.5.3"

[dependencies]
httparse = "1.1.2"
log = "0.3.6"
mio = { branch="v0.5.x", git = "https://github.com/tickbh/mio.git"}
rand = "0.3.14"
sha1 = "0.2.0"
url = "1.2.0"
td_revent = "0.1.5"

[dependencies.libc]
optional = true
version = "0.2.15"

[dependencies.libz-sys]
optional = true
version = "1.0.5"

[dependencies.openssl]
optional = true
version = "0.7.14"

[dev-dependencies]
clap = "2.10.0"
env_logger = "0.3.4"
term = "0.4.4"
time = "0.1.35"

[features]
default = []
permessage-deflate = ["libz-sys", "libc"]
ssl = ["openssl"]
